version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Go vet
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis (includes gosimple)
    - unused        # Detect unused code
    - misspell      # Check for misspellings
    - gosec         # Security checks
    - gocritic      # Comprehensive linter
    - gocyclo       # Cyclomatic complexity
    - dupl          # Duplicate code detection
    - unparam       # Unused function parameters
    - unconvert     # Unnecessary type conversions
    - prealloc      # Preallocate slices
    - copyloopvar   # Loop variable capture
    - nilerr        # Nil error returns
    - bodyclose     # HTTP body close
    - noctx         # HTTP request without context

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Allow _ = func() for explicit error ignoring
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
      - fmt.Fprintf
      - fmt.Fprint
      - fmt.Fprintln

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked - covered by errcheck
      - G204 # Command injection - required for test scripts

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentedOutCode
      - unnecessaryBlock

  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
      - name: unused-parameter
        disabled: true
      - name: var-naming
        disabled: true

  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gocritic

    # Exclude BPF generated code
    - path: tracer_bpf.*\.go
      linters:
        - all

    # Allow complex main functions
    - path: main\.go
      linters:
        - gocyclo

    # Allow complex CLI root command
    - path: cmd/root\.go
      linters:
        - gocyclo
