version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: azazel
    main: .
    binary: azazel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/azazel/cmd.Version={{.Version}}
    flags:
      - -trimpath

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CLAUDE.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Security Updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: beelzebub-labs
    name: azazel
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## Azazel {{ .Tag }} Release

    A lightweight eBPF-based runtime security tracer for malware analysis sandboxes.
  footer: |
    **Full Changelog**: https://github.com/beelzebub-labs/azazel/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Installation

    ### Binary
    ```bash
    # Download and extract
    wget https://github.com/beelzebub-labs/azazel/releases/download/{{ .Tag }}/azazel_linux_amd64.tar.gz
    tar xzf azazel_linux_amd64.tar.gz
    sudo mv azazel /usr/local/bin/
    ```

    ### Docker
    ```bash
    docker pull ghcr.io/beelzebub-labs/azazel:{{ .Tag }}
    ```

    ### Requirements
    - Linux kernel 5.8+ with BTF support
    - Root privileges or CAP_BPF, CAP_PERFMON, CAP_NET_ADMIN, CAP_SYS_ADMIN
