#!/bin/bash
# analyze.sh — Automated malware analysis script
# Usage: sudo ./analyze.sh <sample_path> [timeout_seconds]
set -euo pipefail

SAMPLE="${1:-}"
TIMEOUT="${2:-60}"
OUTPUT_DIR="./output"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

if [ -z "$SAMPLE" ]; then
    echo "Usage: $0 <sample_path> [timeout_seconds]"
    echo "Example: $0 ./samples/malware.elf 30"
    exit 1
fi

if [ ! -f "$SAMPLE" ]; then
    echo "Error: Sample not found: $SAMPLE"
    exit 1
fi

if [ "$(id -u)" -ne 0 ]; then
    echo "Error: Must run as root (needed for eBPF)"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

EVENTS_FILE="$OUTPUT_DIR/events_${TIMESTAMP}.json"
REPORT_FILE="$OUTPUT_DIR/report_${TIMESTAMP}.md"
SAMPLE_NAME=$(basename "$SAMPLE")

echo "============================================"
echo " Azazel — Malware Analysis"
echo "============================================"
echo ""

# Compute hashes
echo "[*] Sample: $SAMPLE_NAME"
echo "[*] Computing hashes..."
SHA256=$(sha256sum "$SAMPLE" | awk '{print $1}')
MD5=$(md5sum "$SAMPLE" | awk '{print $1}')
SHA1=$(sha1sum "$SAMPLE" | awk '{print $1}')
echo "    SHA256: $SHA256"
echo "    MD5:    $MD5"
echo "    SHA1:   $SHA1"
echo ""

# Start tracer
echo "[*] Starting Azazel..."
./bin/azazel --output "$EVENTS_FILE" --no-summary &
TRACER_PID=$!
sleep 2

if ! kill -0 $TRACER_PID 2>/dev/null; then
    echo "Error: Tracer failed to start"
    exit 1
fi

# Run sample in isolated container
echo "[*] Launching sample in sandbox (timeout: ${TIMEOUT}s)..."
CONTAINER_ID=$(docker run -d \
    --cap-drop ALL \
    --cap-add NET_RAW \
    --cap-add SYS_PTRACE \
    --cpus 1 \
    --memory 512m \
    --network none \
    --tmpfs /tmp:size=64M \
    -v "$(realpath "$SAMPLE")":/sample:ro \
    ubuntu:22.04 \
    timeout "$TIMEOUT" /sample 2>/dev/null || true)

if [ -n "$CONTAINER_ID" ]; then
    echo "[*] Sandbox container: ${CONTAINER_ID:0:12}"
    # Wait for completion or timeout
    docker wait "$CONTAINER_ID" 2>/dev/null || true
    docker rm -f "$CONTAINER_ID" 2>/dev/null || true
else
    echo "[*] Warning: Could not start sandbox container"
fi

sleep 2

# Stop tracer
echo "[*] Stopping tracer..."
kill -SIGTERM $TRACER_PID 2>/dev/null
wait $TRACER_PID 2>/dev/null || true
sleep 1

# Generate report
echo "[*] Generating report..."

EVENT_COUNT=$(wc -l < "$EVENTS_FILE" 2>/dev/null || echo "0")

cat > "$REPORT_FILE" << REPORT_EOF
# Azazel Analysis Report

**Date:** $(date -Iseconds)
**Sample:** $SAMPLE_NAME
**Timeout:** ${TIMEOUT}s

## Sample Hashes

| Algorithm | Hash |
|-----------|------|
| SHA256 | \`$SHA256\` |
| MD5 | \`$MD5\` |
| SHA1 | \`$SHA1\` |

## Event Summary

**Total events captured:** $EVENT_COUNT

### Event Types

| Event Type | Count |
|------------|-------|
$(jq -r '.event_type' "$EVENTS_FILE" 2>/dev/null | sort | uniq -c | sort -rn | awk '{printf "| %s | %d |\n", $2, $1}')

### Process Executions

$(jq -r 'select(.event_type=="process_exec") | "- \(.filename) (pid=\(.pid) comm=\(.comm))"' "$EVENTS_FILE" 2>/dev/null | head -50)

### Network Connections

$(jq -r 'select(.event_type=="net_connect") | "- \(.dst_addr):\(.dst_port) (pid=\(.pid) comm=\(.comm))"' "$EVENTS_FILE" 2>/dev/null | head -50)

### DNS Queries

$(jq -r 'select(.event_type=="net_dns") | "- server=\(.server_addr) (pid=\(.pid) comm=\(.comm))"' "$EVENTS_FILE" 2>/dev/null | head -50)

### File Operations

$(jq -r 'select(.event_type=="file_open" and .filename != null) | "- \(.event_type): \(.filename)"' "$EVENTS_FILE" 2>/dev/null | sort -u | head -50)

## Security Alerts

$(jq -r 'select(.event_type=="ptrace") | "- **[HIGH]** ptrace detected (pid=\(.pid) comm=\(.comm))"' "$EVENTS_FILE" 2>/dev/null)
$(jq -r 'select(.event_type=="mmap_exec") | "- **[CRITICAL]** mmap EXEC detected (pid=\(.pid) comm=\(.comm))"' "$EVENTS_FILE" 2>/dev/null)
$(jq -r 'select(.event_type=="module_load") | "- **[HIGH]** module load detected (pid=\(.pid) comm=\(.comm))"' "$EVENTS_FILE" 2>/dev/null)

---
*Generated by Azazel*
REPORT_EOF

echo ""
echo "============================================"
echo " Analysis Complete"
echo "============================================"
echo " Events: $EVENTS_FILE ($EVENT_COUNT events)"
echo " Report: $REPORT_FILE"
echo "============================================"
