// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package tracer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTracer returns the embedded CollectionSpec for tracer.
func loadTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tracer: %w", err)
	}

	return spec, err
}

// loadTracerObjects loads tracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tracerObjects
//	*tracerPrograms
//	*tracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerSpecs struct {
	tracerProgramSpecs
	tracerMapSpecs
	tracerVariableSpecs
}

// tracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerProgramSpecs struct {
	TraceAccept4     *ebpf.ProgramSpec `ebpf:"trace_accept4"`
	TraceBind        *ebpf.ProgramSpec `ebpf:"trace_bind"`
	TraceClone       *ebpf.ProgramSpec `ebpf:"trace_clone"`
	TraceConnect     *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceExecve      *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceFinitModule *ebpf.ProgramSpec `ebpf:"trace_finit_module"`
	TraceListen      *ebpf.ProgramSpec `ebpf:"trace_listen"`
	TraceMmap        *ebpf.ProgramSpec `ebpf:"trace_mmap"`
	TraceOpenat      *ebpf.ProgramSpec `ebpf:"trace_openat"`
	TraceProcessExit *ebpf.ProgramSpec `ebpf:"trace_process_exit"`
	TracePtrace      *ebpf.ProgramSpec `ebpf:"trace_ptrace"`
	TraceRead        *ebpf.ProgramSpec `ebpf:"trace_read"`
	TraceRenameat2   *ebpf.ProgramSpec `ebpf:"trace_renameat2"`
	TraceSendto      *ebpf.ProgramSpec `ebpf:"trace_sendto"`
	TraceUdpSendmsg  *ebpf.ProgramSpec `ebpf:"trace_udp_sendmsg"`
	TraceUnlinkat    *ebpf.ProgramSpec `ebpf:"trace_unlinkat"`
	TraceWrite       *ebpf.ProgramSpec `ebpf:"trace_write"`
}

// tracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerMapSpecs struct {
	ContainerFilter *ebpf.MapSpec `ebpf:"container_filter"`
	Events          *ebpf.MapSpec `ebpf:"events"`
	TracerConfig    *ebpf.MapSpec `ebpf:"tracer_config"`
}

// tracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerVariableSpecs struct {
}

// tracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerObjects struct {
	tracerPrograms
	tracerMaps
	tracerVariables
}

func (o *tracerObjects) Close() error {
	return _TracerClose(
		&o.tracerPrograms,
		&o.tracerMaps,
	)
}

// tracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerMaps struct {
	ContainerFilter *ebpf.Map `ebpf:"container_filter"`
	Events          *ebpf.Map `ebpf:"events"`
	TracerConfig    *ebpf.Map `ebpf:"tracer_config"`
}

func (m *tracerMaps) Close() error {
	return _TracerClose(
		m.ContainerFilter,
		m.Events,
		m.TracerConfig,
	)
}

// tracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerVariables struct {
}

// tracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerPrograms struct {
	TraceAccept4     *ebpf.Program `ebpf:"trace_accept4"`
	TraceBind        *ebpf.Program `ebpf:"trace_bind"`
	TraceClone       *ebpf.Program `ebpf:"trace_clone"`
	TraceConnect     *ebpf.Program `ebpf:"trace_connect"`
	TraceExecve      *ebpf.Program `ebpf:"trace_execve"`
	TraceFinitModule *ebpf.Program `ebpf:"trace_finit_module"`
	TraceListen      *ebpf.Program `ebpf:"trace_listen"`
	TraceMmap        *ebpf.Program `ebpf:"trace_mmap"`
	TraceOpenat      *ebpf.Program `ebpf:"trace_openat"`
	TraceProcessExit *ebpf.Program `ebpf:"trace_process_exit"`
	TracePtrace      *ebpf.Program `ebpf:"trace_ptrace"`
	TraceRead        *ebpf.Program `ebpf:"trace_read"`
	TraceRenameat2   *ebpf.Program `ebpf:"trace_renameat2"`
	TraceSendto      *ebpf.Program `ebpf:"trace_sendto"`
	TraceUdpSendmsg  *ebpf.Program `ebpf:"trace_udp_sendmsg"`
	TraceUnlinkat    *ebpf.Program `ebpf:"trace_unlinkat"`
	TraceWrite       *ebpf.Program `ebpf:"trace_write"`
}

func (p *tracerPrograms) Close() error {
	return _TracerClose(
		p.TraceAccept4,
		p.TraceBind,
		p.TraceClone,
		p.TraceConnect,
		p.TraceExecve,
		p.TraceFinitModule,
		p.TraceListen,
		p.TraceMmap,
		p.TraceOpenat,
		p.TraceProcessExit,
		p.TracePtrace,
		p.TraceRead,
		p.TraceRenameat2,
		p.TraceSendto,
		p.TraceUdpSendmsg,
		p.TraceUnlinkat,
		p.TraceWrite,
	)
}

func _TracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracer_bpfel.o
var _TracerBytes []byte
